// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBPigzqPLB5HRiW2noB0RTQaXQGPuJbc',
    appId: '1:512577927547:web:11063fe2221515f9c565de',
    messagingSenderId: '512577927547',
    projectId: 'gothic-tempest-453915-a8',
    authDomain: 'gothic-tempest-453915-a8.firebaseapp.com',
    storageBucket: 'gothic-tempest-453915-a8.firebasestorage.app',
    measurementId: 'G-WVNQXJ6MSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3c3EwVbUlcWnqJeHCRwxJgzweBN14rk',
    appId: '1:512577927547:android:86a7ecd6148ff76dc565de',
    messagingSenderId: '512577927547',
    projectId: 'gothic-tempest-453915-a8',
    storageBucket: 'gothic-tempest-453915-a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtPm-LNqlBFQF-B98ZTisR_lYkyWjaaI',
    appId: '1:512577927547:ios:eabd19f4f23b0e41c565de',
    messagingSenderId: '512577927547',
    projectId: 'gothic-tempest-453915-a8',
    storageBucket: 'gothic-tempest-453915-a8.firebasestorage.app',
    androidClientId: '512577927547-9h7o5l6tv7ph0vmnfttv2khln255kqel.apps.googleusercontent.com',
    iosClientId: '512577927547-9ncuv8f1jjki2dtko7mhh1mii8rdh8ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlrebasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtPm-LNqlBFQF-B98ZTisR_lYkyWjaaI',
    appId: '1:512577927547:ios:eabd19f4f23b0e41c565de',
    messagingSenderId: '512577927547',
    projectId: 'gothic-tempest-453915-a8',
    storageBucket: 'gothic-tempest-453915-a8.firebasestorage.app',
    androidClientId: '512577927547-9h7o5l6tv7ph0vmnfttv2khln255kqel.apps.googleusercontent.com',
    iosClientId: '512577927547-9ncuv8f1jjki2dtko7mhh1mii8rdh8ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlrebasee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADBPigzqPLB5HRiW2noB0RTQaXQGPuJbc',
    appId: '1:512577927547:web:aec2598d26a0a4a6c565de',
    messagingSenderId: '512577927547',
    projectId: 'gothic-tempest-453915-a8',
    authDomain: 'gothic-tempest-453915-a8.firebaseapp.com',
    storageBucket: 'gothic-tempest-453915-a8.firebasestorage.app',
    measurementId: 'G-8BD158GQSC',
  );
}
